### PR TITLE
add input driver, input libs, keyboard keymaps, string functions

### PR DESCRIPTION
**Pull request by TimonGaertner**
* input-device driver
* keyboard_keymap
* keyboard_stringmap
* string functions: append inbetween, remove inbetween
* read-input lib
* input_to_text lib

### CODE REVIEW

**Comment by TimonGaertner** [comment]
#https://github.com/lennardwalter/yaku/pull/16 only works if this (string.h) was merged

**Comment by lennardwalter** [comment]
^^ resolved conflicts

**Comment by lennardwalter** [comment]
it's not great that we have two `string.h` files in `lib/` and `thirdparty`. just put the functions in `lib/string.(c|h)` directly into the files where they are needed (for now).

**Comment by TimonGaertner** [comment]
> it's not great that we have two `string.h` files in `lib/` and `thirdparty`. just put the functions in `lib/string.(c|h)` directly into the files where they are needed (for now).

done but not tested:

22f50db
127f311
a20bbc9
8313173

**Comment by TimonGaertner** [comment]
tested
22f50db
127f311
a20bbc9
8313173

**Pull request merged**
